#pragma kernel CSMain

#include "Assets/FluidSimulation/FluidSimulationLibrary.hlsl"

StructuredBuffer<CellData> _CellDatas;
RWTexture2D<float4> _FluidTexture;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	uint index = id.x + id.y * _Resolution.x;
	if(index >= _CellDatas.Length) {
		return;
	}

	CellData cellData = _CellDatas[index];

	_FluidTexture[id.xy] = float4(cellData.color.rgb, cellData.density);
}